import type { Mission } from "../../platform/types";

export const sqlDetectiveMissions: Mission[] = [
  {
    id: "sql-select-columns",
    title: "Read the Customer File",
    eyebrow: "BEGINNER / 01",
    summary: "Select only the customer details the support team requested.",
    objective: "Return each customer's name and email. Do not expose the other columns.",
    difficulty: "Beginner",
    points: 100,
    repository: ["customers", "id · name · email · status · created_at", "sample: 101 · Ada Chen · ada@example.com · active"],
    repositorySnapshots: [{ afterStep: 1, lines: ["name               email", "Ada Chen           ada@example.com", "Malik Jones        malik@example.com", "3 rows · 2 columns"] }],
    steps: [{
      id: "select-customer-columns",
      objective: "Select only name and email from the customers table.",
      acceptedCommands: ["SELECT name, email FROM customers;"],
      hint: "Name the two columns after SELECT, then add FROM customers.",
      success: "Correct: the query returns just the two requested fields, avoiding unnecessary customer data.",
      incorrectFeedback: [
        { command: "SELECT * FROM customers;", message: "SELECT * returns every column, including fields support did not request. Select name and email explicitly to limit the data." },
        { command: "SELECT name FROM customers;", message: "The result is missing the email column. Return both requested fields: name and email." },
      ],
    }],
  },
  {
    id: "sql-filter-rows",
    title: "Find Active Accounts",
    eyebrow: "BEGINNER / 02",
    summary: "Filter a customer list to the accounts that can sign in.",
    objective: "Return the names of customers whose status is active.",
    difficulty: "Beginner",
    points: 110,
    repository: ["customers", "name · status", "active · Ada Chen", "inactive · Jo Park"],
    repositorySnapshots: [{ afterStep: 1, lines: ["name", "Ada Chen", "Priya Shah", "2 active customers"] }],
    steps: [{
      id: "filter-active-customers",
      objective: "Select customer names and keep only rows with status equal to active.",
      acceptedCommands: ["SELECT name FROM customers WHERE status = 'active';"],
      hint: "Use WHERE status = 'active' to keep only matching rows.",
      success: "Correct: WHERE filters rows before they are returned, so inactive accounts are excluded.",
      incorrectFeedback: [
        { command: "SELECT name FROM customers;", message: "Without a WHERE clause, this returns inactive customers too. Filter status to 'active'." },
        { command: "SELECT name FROM customers WHERE status = 'inactive';", message: "This selects the opposite group. The request is for customers whose status is 'active'." },
      ],
    }],
  },
  {
    id: "sql-sort-limit",
    title: "Latest Signups",
    eyebrow: "BEGINNER / 03",
    summary: "Show the three most recently registered customers.",
    objective: "Return the three newest customers by signup date, newest first.",
    difficulty: "Beginner",
    points: 120,
    repository: ["customers", "id · name · created_at", "4 sample customers · dates span January to April"],
    repositorySnapshots: [{ afterStep: 1, lines: ["name       created_at", "Priya Shah 2026-04-12", "Ada Chen  2026-04-08", "Malik Jones 2026-03-29", "3 rows · newest first"] }],
    steps: [{
      id: "sort-and-limit-signups",
      objective: "Sort by created_at descending and return only three rows.",
      acceptedCommands: ["SELECT name, created_at FROM customers ORDER BY created_at DESC LIMIT 3;"],
      hint: "ORDER BY created_at DESC puts newest dates first; LIMIT 3 caps the result.",
      success: "Correct: descending order puts the newest signups first, and LIMIT returns exactly three.",
      incorrectFeedback: [
        { command: "SELECT name, created_at FROM customers ORDER BY created_at ASC LIMIT 3;", message: "ASC puts the oldest signups first. Use DESC to show the newest customers first." },
        { command: "SELECT name, created_at FROM customers ORDER BY created_at DESC;", message: "The sort direction is right, but without LIMIT the query returns every signup instead of three." },
      ],
    }],
  },
  {
    id: "sql-count-orders",
    title: "Count Paid Orders",
    eyebrow: "BEGINNER / 04",
    summary: "Give finance one reliable count of completed purchases.",
    objective: "Count only orders whose status is paid.",
    difficulty: "Beginner",
    points: 130,
    repository: ["orders", "id · customer_id · total · status", "5 sample orders · 3 paid"],
    repositorySnapshots: [{ afterStep: 1, lines: ["paid_orders", "3", "one aggregate row"] }],
    steps: [{
      id: "count-paid-orders",
      objective: "Use COUNT to count rows filtered to paid orders.",
      acceptedCommands: ["SELECT COUNT(*) AS paid_orders FROM orders WHERE status = 'paid';"],
      hint: "COUNT(*) counts matching rows; filter status in the WHERE clause.",
      success: "Correct: COUNT(*) counts rows, and WHERE ensures pending or cancelled orders are not included.",
      incorrectFeedback: [
        { command: "SELECT COUNT(*) AS paid_orders FROM orders;", message: "This counts every order, including pending and cancelled ones. Filter to status = 'paid' before counting." },
        { command: "SELECT SUM(total) AS paid_orders FROM orders WHERE status = 'paid';", message: "SUM adds the order totals; it does not count orders. Use COUNT(*) for the requested number of rows." },
      ],
    }],
  },
  {
    id: "sql-group-revenue",
    title: "Revenue by Category",
    eyebrow: "INTERMEDIATE / 01",
    summary: "Turn line items into a category-level revenue report.",
    objective: "Calculate total quantity-times-price revenue per category.",
    difficulty: "Intermediate",
    points: 160,
    repository: ["order_items", "category · quantity · unit_price", "4 sample line items across 2 categories"],
    repositorySnapshots: [{ afterStep: 1, lines: ["category    revenue", "books       45.00", "hardware    80.00", "2 grouped rows"] }],
    steps: [{
      id: "aggregate-category-revenue",
      objective: "Group line items by category and sum quantity multiplied by unit_price.",
      acceptedCommands: ["SELECT category, SUM(quantity * unit_price) AS revenue FROM order_items GROUP BY category;"],
      hint: "Aggregate the row-level expression with SUM, then GROUP BY category.",
      success: "Correct: grouping creates one row per category, while SUM adds each line's extended price.",
      incorrectFeedback: [
        { command: "SELECT category, SUM(unit_price) AS revenue FROM order_items GROUP BY category;", message: "Summing unit_price ignores how many units were sold. Multiply quantity by unit_price for each line before summing." },
        { command: "SELECT category, SUM(quantity * unit_price) AS revenue FROM order_items;", message: "The sum combines all categories into one total. GROUP BY category produces a separate total for each category." },
      ],
    }],
  },
  {
    id: "sql-inner-join",
    title: "Match Orders to People",
    eyebrow: "INTERMEDIATE / 02",
    summary: "Connect purchases to the customers who placed them.",
    objective: "List each paid order with the customer's name and order total.",
    difficulty: "Intermediate",
    points: 170,
    repository: ["customers: id · name", "orders: id · customer_id · total · status", "orders.customer_id references customers.id"],
    repositorySnapshots: [{ afterStep: 1, lines: ["order_id · customer · total", "5001 · Ada Chen · 45.00", "5004 · Malik Jones · 29.00", "2 paid orders"] }],
    steps: [{
      id: "join-paid-orders",
      objective: "Join orders to customers on customer_id = id and filter to paid orders.",
      acceptedCommands: ["SELECT o.id, c.name, o.total FROM orders o INNER JOIN customers c ON o.customer_id = c.id WHERE o.status = 'paid';"],
      hint: "Join orders o to customers c with o.customer_id = c.id, then filter o.status.",
      success: "Correct: the join uses the foreign-key relationship, and the filter keeps only paid purchases.",
      incorrectFeedback: [
        { command: "SELECT o.id, c.name, o.total FROM orders o INNER JOIN customers c ON o.id = c.id WHERE o.status = 'paid';", message: "Orders.id identifies an order, not its customer. Match customers.id to orders.customer_id." },
        { command: "SELECT o.id, c.name, o.total FROM orders o INNER JOIN customers c ON o.customer_id = c.id;", message: "The join is correct, but it also includes pending and cancelled orders. Filter to paid status." },
      ],
    }],
  },
  {
    id: "sql-left-join",
    title: "Spot Customers with No Orders",
    eyebrow: "INTERMEDIATE / 03",
    summary: "Find customers who have never placed an order.",
    objective: "Return the names of customers with no matching order.",
    difficulty: "Intermediate",
    points: 180,
    repository: ["customers: id · name", "orders: id · customer_id", "customer 103 has no orders"],
    repositorySnapshots: [{ afterStep: 1, lines: ["name", "Jo Park", "1 customer without orders"] }],
    steps: [{
      id: "find-customers-without-orders",
      objective: "Use a LEFT JOIN and keep rows where the order id is NULL.",
      acceptedCommands: ["SELECT c.name FROM customers c LEFT JOIN orders o ON o.customer_id = c.id WHERE o.id IS NULL;"],
      hint: "A LEFT JOIN preserves every customer; unmatched order columns are NULL.",
      success: "Correct: the LEFT JOIN keeps every customer, and NULL identifies customers without a matching order.",
      incorrectFeedback: [
        { command: "SELECT c.name FROM customers c INNER JOIN orders o ON o.customer_id = c.id WHERE o.id IS NULL;", message: "An INNER JOIN removes customers with no order before filtering. Use LEFT JOIN to preserve them." },
        { command: "SELECT c.name FROM customers c LEFT JOIN orders o ON o.customer_id = c.id WHERE o.id IS NOT NULL;", message: "IS NOT NULL selects customers who do have orders. Find missing matches with IS NULL." },
      ],
    }],
  },
  {
    id: "sql-subquery-average",
    title: "Above-Average Products",
    eyebrow: "INTERMEDIATE / 04",
    summary: "Find products priced above the catalog average.",
    objective: "Return product names and prices that exceed the average price.",
    difficulty: "Intermediate",
    points: 190,
    repository: ["products", "name · price", "sample catalog average: 25.00"],
    repositorySnapshots: [{ afterStep: 1, lines: ["name          price", "Desk Lamp     39.00", "Keyboard      59.00", "2 products above average"] }],
    steps: [{
      id: "compare-with-average",
      objective: "Compare each price to a scalar subquery that calculates the average price.",
      acceptedCommands: ["SELECT name, price FROM products WHERE price > (SELECT AVG(price) FROM products);"],
      hint: "Put SELECT AVG(price) FROM products inside parentheses in the WHERE comparison.",
      success: "Correct: the scalar subquery computes one benchmark value, then the outer query keeps higher-priced products.",
      incorrectFeedback: [
        { command: "SELECT name, price FROM products WHERE price > AVG(price);", message: "AVG is an aggregate and cannot be compared to each row this way in WHERE. Calculate the average in a scalar subquery." },
        { command: "SELECT name, price FROM products WHERE price < (SELECT AVG(price) FROM products);", message: "The comparison finds below-average products. Use > to return prices above the average." },
      ],
    }],
  },
  {
    id: "sql-monthly-cte",
    title: "Monthly Revenue CTE",
    eyebrow: "ADVANCED / 01",
    summary: "Build a readable monthly revenue report from paid orders.",
    objective: "Use a CTE to calculate monthly revenue from paid orders.",
    difficulty: "Advanced",
    points: 210,
    repository: ["orders", "created_at · total · status", "timestamps are stored in UTC"],
    repositorySnapshots: [{ afterStep: 1, lines: ["month      revenue", "2026-01    12400.00", "2026-02    15650.00", "one row per month"] }],
    steps: [{
      id: "monthly-revenue-cte",
      objective: "Define a paid_orders CTE and group its rows by month.",
      acceptedCommands: ["WITH paid_orders AS (SELECT created_at, total FROM orders WHERE status = 'paid') SELECT DATE_TRUNC('month', created_at) AS month, SUM(total) AS revenue FROM paid_orders GROUP BY DATE_TRUNC('month', created_at) ORDER BY month;"],
      hint: "Start with WITH paid_orders AS (...), then aggregate its filtered rows by DATE_TRUNC('month', created_at).",
      success: "Correct: the CTE names the filtered input clearly, and the outer query aggregates paid revenue by month.",
      incorrectFeedback: [
        { command: "SELECT DATE_TRUNC('month', created_at) AS month, SUM(total) AS revenue FROM orders GROUP BY DATE_TRUNC('month', created_at);", message: "This groups all orders, including unpaid ones. Filter paid orders in a CTE before aggregating." },
        { command: "WITH paid_orders AS (SELECT created_at, total FROM orders WHERE status = 'paid') SELECT DATE_TRUNC('month', created_at) AS month, SUM(total) AS revenue FROM paid_orders GROUP BY DATE_TRUNC('month', created_at);", message: "The monthly totals are right, but the requested report is ordered by month. Add ORDER BY month." },
      ],
    }],
  },
  {
    id: "sql-rank-per-category",
    title: "Rank Bestsellers",
    eyebrow: "ADVANCED / 02",
    summary: "Rank products within each category without mixing categories.",
    objective: "Assign a price rank per category, highest priced first.",
    difficulty: "Advanced",
    points: 220,
    repository: ["products", "id · name · category · price", "window functions are supported"],
    repositorySnapshots: [{ afterStep: 1, lines: ["category · name · price_rank", "books · SQL Field Guide · 1", "books · Data Patterns · 2", "rank restarts per category"] }],
    steps: [{
      id: "rank-products-by-category",
      objective: "Use DENSE_RANK partitioned by category and ordered by price descending.",
      acceptedCommands: ["SELECT name, category, price, DENSE_RANK() OVER (PARTITION BY category ORDER BY price DESC) AS price_rank FROM products;"],
      hint: "DENSE_RANK() OVER (...) needs PARTITION BY category and ORDER BY price DESC.",
      success: "Correct: PARTITION BY restarts ranking for each category; DESC gives the highest price rank 1.",
      incorrectFeedback: [
        { command: "SELECT name, category, price, DENSE_RANK() OVER (ORDER BY price DESC) AS price_rank FROM products;", message: "Without PARTITION BY category, products from every category compete in one global ranking." },
        { command: "SELECT name, category, price, DENSE_RANK() OVER (PARTITION BY category ORDER BY price ASC) AS price_rank FROM products;", message: "ASC ranks the cheapest item first. Use DESC so the highest-priced product ranks first." },
      ],
    }],
  },
  {
    id: "sql-running-total",
    title: "Running Revenue",
    eyebrow: "ADVANCED / 03",
    summary: "Track cumulative daily revenue as the month progresses.",
    objective: "Show each day and its running total of paid revenue in date order.",
    difficulty: "Advanced",
    points: 230,
    repository: ["orders", "created_at · total · status", "multiple paid orders can share a day"],
    repositorySnapshots: [{ afterStep: 1, lines: ["day · daily_revenue · running_revenue", "2026-03-01 · 20.00 · 20.00", "2026-03-02 · 35.00 · 55.00"] }],
    steps: [{
      id: "calculate-running-revenue",
      objective: "Aggregate paid orders per day, then use a window SUM ordered by day.",
      acceptedCommands: ["WITH daily AS (SELECT CAST(created_at AS DATE) AS day, SUM(total) AS revenue FROM orders WHERE status = 'paid' GROUP BY CAST(created_at AS DATE)) SELECT day, revenue, SUM(revenue) OVER (ORDER BY day) AS running_revenue FROM daily ORDER BY day;"],
      hint: "First group paid orders into daily totals; then SUM that daily value over an ordered window.",
      success: "Correct: daily aggregation prevents same-day orders from becoming separate dates, and the ordered window builds the cumulative total.",
      incorrectFeedback: [
        { command: "SELECT CAST(created_at AS DATE) AS day, SUM(total) OVER (ORDER BY created_at) AS running_revenue FROM orders WHERE status = 'paid';", message: "This window sums individual order rows rather than daily totals. Aggregate by date first, then calculate the running sum." },
        { command: "WITH daily AS (SELECT CAST(created_at AS DATE) AS day, SUM(total) AS revenue FROM orders WHERE status = 'paid' GROUP BY CAST(created_at AS DATE)) SELECT day, revenue, SUM(revenue) OVER () AS running_revenue FROM daily ORDER BY day;", message: "The window has no ORDER BY, so it does not define a running sequence. Order the window by day." },
      ],
    }],
  },
  {
    id: "sql-deduplicate-events",
    title: "Keep the Latest Event",
    eyebrow: "ADVANCED / 04",
    summary: "Deduplicate replayed events while preserving the newest record.",
    objective: "Return exactly the latest event for each event_key.",
    difficulty: "Advanced",
    points: 240,
    repository: ["events", "event_key · payload · received_at", "retries can produce duplicate event_key values"],
    repositorySnapshots: [{ afterStep: 1, lines: ["event_key · payload · received_at", "evt-7 · payment-approved · 2026-04-08 11:02", "one latest row per key"] }],
    steps: [{
      id: "deduplicate-latest-events",
      objective: "Rank events newest-first per event_key and keep rank 1.",
      acceptedCommands: ["WITH ranked AS (SELECT event_key, payload, received_at, ROW_NUMBER() OVER (PARTITION BY event_key ORDER BY received_at DESC) AS row_num FROM events) SELECT event_key, payload, received_at FROM ranked WHERE row_num = 1;"],
      hint: "Use ROW_NUMBER per event_key ordered by received_at DESC, then filter row_num to 1.",
      success: "Correct: each event key is ranked independently, and row number 1 retains only its newest event.",
      incorrectFeedback: [
        { command: "SELECT DISTINCT event_key, payload, received_at FROM events;", message: "DISTINCT only removes identical full rows; it does not choose the newest row when payloads differ. Rank each key by received_at." },
        { command: "WITH ranked AS (SELECT event_key, payload, received_at, ROW_NUMBER() OVER (PARTITION BY event_key ORDER BY received_at ASC) AS row_num FROM events) SELECT event_key, payload, received_at FROM ranked WHERE row_num = 1;", message: "ASC ranks the oldest event first. Use DESC to retain the latest event for each key." },
      ],
    }],
  },
  {
    id: "sql-recursive-hierarchy",
    title: "Trace the Org Chart",
    eyebrow: "EXPERT / 01",
    summary: "Traverse a reporting hierarchy from its root with a recursive CTE.",
    objective: "Return the root employee and all descendants, with their hierarchy depth.",
    difficulty: "Expert",
    points: 260,
    repository: ["employees", "id · name · manager_id", "CEO has manager_id NULL"],
    repositorySnapshots: [{ afterStep: 1, lines: ["name · depth", "Avery Cole · 0", "Rin Patel · 1", "Sam Rivera · 2"] }],
    steps: [{
      id: "walk-employee-hierarchy",
      objective: "Use an anchor row for the CEO and recursively join each employee's direct reports.",
      acceptedCommands: ["WITH RECURSIVE org AS (SELECT id, name, manager_id, 0 AS depth FROM employees WHERE manager_id IS NULL UNION ALL SELECT e.id, e.name, e.manager_id, o.depth + 1 FROM employees e JOIN org o ON e.manager_id = o.id) SELECT name, depth FROM org ORDER BY depth, name;"],
      hint: "The anchor finds the CEO. UNION ALL the recursive step joining employees.manager_id to the current org id.",
      success: "Correct: the anchor seeds the root, and each recursive iteration adds one reporting level with its depth.",
      incorrectFeedback: [
        { command: "WITH RECURSIVE org AS (SELECT id, name, manager_id, 0 AS depth FROM employees WHERE manager_id IS NULL UNION ALL SELECT e.id, e.name, e.manager_id, o.depth + 1 FROM employees e JOIN org o ON e.id = o.manager_id) SELECT name, depth FROM org;", message: "The recursive join is reversed. To find direct reports, match each employee's manager_id to the current org row's id." },
        { command: "SELECT id, name, manager_id FROM employees WHERE manager_id IS NULL;", message: "This returns only the CEO. A recursive CTE is needed to follow manager_id links to every descendant." },
      ],
    }],
  },
  {
    id: "sql-query-plan",
    title: "Rescue the Slow Lookup",
    eyebrow: "EXPERT / 02",
    summary: "Rewrite a non-sargable filter so an index can serve it.",
    objective: "Find events for one account in a timestamp range without wrapping the indexed timestamp column in a function.",
    difficulty: "Expert",
    points: 270,
    repository: ["events", "account_id · created_at · event_type", "indexes: (account_id, created_at)", "table contains 80 million rows"],
    repositorySnapshots: [{ afterStep: 1, lines: ["Index range scan on (account_id, created_at)", "bounded timestamp range", "estimated rows: 420"] }],
    steps: [{
      id: "write-index-friendly-filter",
      objective: "Filter by account_id and a half-open created_at range directly.",
      acceptedCommands: ["SELECT event_type, created_at FROM events WHERE account_id = 42 AND created_at >= TIMESTAMP '2026-05-01 00:00:00' AND created_at < TIMESTAMP '2026-06-01 00:00:00';"],
      hint: "Avoid DATE(created_at): compare the indexed timestamp directly using >= start and < next month.",
      success: "Correct: direct equality and range predicates align with the composite index and keep the timestamp column searchable.",
      incorrectFeedback: [
        { command: "SELECT event_type, created_at FROM events WHERE account_id = 42 AND DATE(created_at) = DATE '2026-05-01';", message: "Wrapping created_at in DATE() can prevent an ordinary index range scan, and this only checks one day. Compare the raw timestamp to a half-open month range." },
        { command: "SELECT event_type, created_at FROM events WHERE DATE(created_at) = DATE '2026-05-01';", message: "This applies a function to the indexed timestamp and omits the account filter. Use account_id = 42 and direct timestamp bounds." },
      ],
    }],
  },
  {
    id: "sql-isolation-safe",
    title: "Protect the Inventory Update",
    eyebrow: "EXPERT / 03",
    summary: "Apply a stock correction atomically and guard against negative inventory.",
    objective: "Decrease the stock for product 77 by three only when at least three units are available, inside a transaction.",
    difficulty: "Expert",
    points: 280,
    repository: ["inventory", "product_id · stock", "product 77 currently has 8 units", "transaction simulation · no real writes"],
    repositorySnapshots: [{ afterStep: 1, lines: ["BEGIN", "UPDATE inventory SET stock = stock - 3", "WHERE product_id = 77 AND stock >= 3", "COMMIT · 5 units remain"] }],
    steps: [{
      id: "guarded-transaction",
      objective: "Begin a transaction, guard the decrement in the UPDATE predicate, then commit.",
      acceptedCommands: ["BEGIN; UPDATE inventory SET stock = stock - 3 WHERE product_id = 77 AND stock >= 3; COMMIT;"],
      hint: "Use one transaction; include stock >= 3 in the UPDATE's WHERE clause so the check and decrement are atomic.",
      success: "Correct: the transaction groups the write, and the predicate prevents the stock from dropping below zero.",
      incorrectFeedback: [
        { command: "BEGIN; UPDATE inventory SET stock = stock - 3 WHERE product_id = 77; COMMIT;", message: "The update has no availability guard. Add stock >= 3 to the WHERE clause so concurrent requests cannot blindly overdraw inventory." },
        { command: "UPDATE inventory SET stock = stock - 3 WHERE product_id = 77 AND stock >= 3;", message: "The predicate is safe, but the write is not wrapped in the requested transaction. Begin and commit the operation as one unit." },
      ],
    }],
  },
  {
    id: "sql-keyset-pagination",
    title: "Page Through the Firehose",
    eyebrow: "EXPERT / 04",
    summary: "Design stable deep pagination for a large event stream.",
    objective: "Fetch the next 100 events after the last seen timestamp and id using the composite cursor.",
    difficulty: "Expert",
    points: 300,
    repository: ["events", "id · account_id · created_at · payload", "index: (account_id, created_at, id)", "table contains 80 million rows"],
    repositorySnapshots: [{ afterStep: 1, lines: ["next 100 rows after cursor", "ordered by created_at, then id", "index-aligned keyset page"] }],
    steps: [{
      id: "keyset-page-events",
      objective: "Use a composite cursor predicate, matching ORDER BY and LIMIT to the index.",
      acceptedCommands: ["SELECT id, created_at, payload FROM events WHERE account_id = 42 AND (created_at, id) > (TIMESTAMP '2026-05-01 12:00:00', 9001) ORDER BY created_at, id LIMIT 100;"],
      hint: "Continue after both cursor fields with a row-value comparison, then order by created_at, id and limit to 100.",
      success: "Correct: keyset pagination resumes from the last seen composite key and avoids scanning/offsetting every earlier page.",
      incorrectFeedback: [
        { command: "SELECT id, created_at, payload FROM events WHERE account_id = 42 ORDER BY created_at, id LIMIT 100 OFFSET 500000;", message: "A deep OFFSET still scans and discards earlier rows, and pages can shift as new events arrive. Use the last seen (created_at, id) cursor." },
        { command: "SELECT id, created_at, payload FROM events WHERE account_id = 42 AND created_at > TIMESTAMP '2026-05-01 12:00:00' ORDER BY created_at, id LIMIT 100;", message: "Using only the timestamp can skip rows that share the cursor time. Include id as the tie-breaker in the cursor predicate." },
      ],
    }],
  },
];
