import type { Mission } from "../../platform/types";

export const gitQuestMissions: Mission[] = [
  {
    id: "first-commit",
    title: "First Commit",
    eyebrow: "01 / Foundations",
    summary: "Initialize a repository and save your first snapshot.",
    objective: "Set up this project in Git, stage its README, and commit the initial version.",
    difficulty: "Beginner",
    points: 100,
    repository: ["README.md        untracked", "src/app.ts       untracked"],
    repositorySnapshots: [
      { afterStep: 1, lines: ["README.md        untracked", "src/app.ts       untracked", "repository initialized"] },
      { afterStep: 2, lines: ["A  README.md", "?? src/app.ts", "repository initialized"] },
      { afterStep: 3, lines: ["main  ● 3a7f9c  Initial commit", "working tree: clean"] },
    ],
    steps: [
      { id: "init", objective: "Initialize a repository in this project.", acceptedCommands: ["git init"], hint: "The command that creates a new repository is git init.", success: "Repository initialized. Git can now track snapshots in this folder." },
      { id: "stage-readme", objective: "Stage the README file for your first snapshot.", acceptedCommands: ["git add README.md"], hint: "Use git add followed by the exact file name: README.md.", success: "README.md is staged. The index now contains the file you selected." },
      { id: "commit", objective: "Create your first commit with a clear message.", acceptedCommands: ["git commit -m \"Initial commit\"", "git commit -m 'Initial commit'"], hint: "Commit the staged snapshot with: git commit -m \"Initial commit\".", success: "Your first commit is saved. A commit records the staged snapshot." },
    ],
  },
  {
    id: "missing-change",
    title: "The Missing Change",
    eyebrow: "02 / Working tree",
    summary: "Inspect a noisy working tree and commit only the requested file.",
    objective: "A generated file should stay out of version control. Find and stage only the checkout fix.",
    difficulty: "Beginner",
    points: 120,
    repository: [" M  src/checkout.ts", "?? debug.log", " M  package-lock.json"],
    repositorySnapshots: [
      { afterStep: 2, lines: ["M  src/checkout.ts (staged)", "?? debug.log", " M  package-lock.json"] },
      { afterStep: 3, lines: ["main  ● 45a27e  Fix checkout validation", "?? debug.log", " M  package-lock.json"] },
    ],
    steps: [
      { id: "inspect", objective: "Inspect the working tree before deciding what to stage.", acceptedCommands: ["git status"], hint: "git status lists staged, changed, and untracked files.", success: "You found the checkout fix, a debug log, and an unrelated lockfile change." },
      { id: "stage-file", objective: "Stage only src/checkout.ts.", acceptedCommands: ["git add src/checkout.ts"], hint: "Stage the requested file by path; don't use git add . here.", success: "Only the checkout fix is staged. The debug log and lockfile remain untouched." },
      { id: "commit-fix", objective: "Commit the focused change as \"Fix checkout validation\".", acceptedCommands: ["git commit -m \"Fix checkout validation\"", "git commit -m 'Fix checkout validation'"], hint: "Use git commit -m \"Fix checkout validation\".", success: "The focused fix is committed without the generated file or unrelated lockfile." },
    ],
  },
  {
    id: "branch-out",
    title: "Branch Out",
    eyebrow: "03 / Branching",
    summary: "Start a feature without putting unfinished work on main.",
    objective: "Create an isolated feature branch, then save the change there.",
    difficulty: "Beginner",
    points: 140,
    branch: "main",
    branchProgression: [{ afterStep: 1, branch: "feature/dark-mode" }],
    repository: ["main  ●  a72bc9  Add account shell", "working tree: clean"],
    repositorySnapshots: [
      { afterStep: 1, lines: ["main  ●  a72bc9  Add account shell", "feature/dark-mode  ← HEAD"] },
      { afterStep: 2, lines: ["feature/dark-mode  ← HEAD", "A  src/theme.css (staged)"] },
      { afterStep: 3, lines: ["feature/dark-mode  ● b281ac  Add dark theme", "main  ● a72bc9  Add account shell"] },
    ],
    steps: [
      { id: "create-branch", objective: "Create and switch to feature/dark-mode.", acceptedCommands: ["git switch -c feature/dark-mode", "git checkout -b feature/dark-mode"], hint: "Create and switch in one step with git switch -c feature/dark-mode.", success: "You are now on feature/dark-mode. Main remains unchanged." },
      { id: "stage-theme", objective: "Stage the new theme stylesheet.", acceptedCommands: ["git add src/theme.css"], hint: "Stage src/theme.css, not every file in the working tree.", success: "The theme change is staged on the feature branch." },
      { id: "commit-theme", objective: "Commit the feature as \"Add dark theme\".", acceptedCommands: ["git commit -m \"Add dark theme\"", "git commit -m 'Add dark theme'"], hint: "Save the staged change with git commit -m \"Add dark theme\".", success: "The feature is recorded independently and ready for review." },
    ],
  },
  {
    id: "merge-it",
    title: "Merge It",
    eyebrow: "04 / Integration",
    summary: "Integrate reviewed work while keeping the protected branch safe.",
    objective: "The feature is reviewed and checks are green. Merge it into main using the normal collaboration flow.",
    difficulty: "Beginner",
    points: 160,
    branch: "feature/profile",
    branchProgression: [{ afterStep: 1, branch: "main" }],
    repository: ["main                 ● c5120a", "  └─ feature/profile  ● 92a4f1", "MR !248 · approved · CI passing"],
    repositorySnapshots: [
      { afterStep: 1, lines: ["main  ← HEAD  ● c5120a", "feature/profile  ● 92a4f1", "MR !248 · approved · CI passing"] },
      { afterStep: 2, lines: ["main  ● 08df20  Merge feature/profile", "  ├─ c5120a  Previous main", "  └─ 92a4f1  Feature profile"] },
    ],
    steps: [
      { id: "switch-main", objective: "Switch to main before integrating the feature.", acceptedCommands: ["git switch main", "git checkout main"], hint: "Use git switch main to check out the target branch.", success: "You are on main. The reviewed feature branch is ready to merge." },
      { id: "merge-feature", objective: "Merge feature/profile into the current branch.", acceptedCommands: ["git merge feature/profile"], hint: "Integrate the reviewed branch with git merge feature/profile.", success: "The reviewed feature is now integrated. Branch protections and review remain part of the team workflow." },
    ],
  },
  {
    id: "conflict",
    title: "Conflict!",
    eyebrow: "05 / Collaboration",
    summary: "Resolve overlapping edits by intent, not by blindly choosing a side.",
    objective: "Both teams agree payment requests need a configurable 60-second timeout. Preserve that behavior and finish the merge.",
    difficulty: "Intermediate",
    points: 200,
    repository: ["<<<<<<< HEAD", "timeout = 30", "=======", "timeout = 60", ">>>>>>> feature/payment"],
    repositorySnapshots: [
      { afterStep: 1, lines: ["timeout = 60", "conflict markers removed", "M  config/payment.ts (staged)"] },
      { afterStep: 2, lines: ["main  ● 61e2a0  Resolve payment timeout conflict", "working tree: clean"] },
    ],
    steps: [
      { id: "resolve-file", objective: "Choose the agreed 60-second behavior, then stage the resolved file.", acceptedCommands: ["git add config/payment.ts"], hint: "The teams agreed to a 60-second timeout. Select that value, then stage config/payment.ts.", success: "The agreed behavior is staged. A clean resolution preserves intent, not just syntax.", choices: [{ id: "30", label: "Keep timeout = 30" }, { id: "60", label: "Keep timeout = 60" }, { id: "configurable", label: "Make it configurable" }], correctChoiceId: "60", choiceFeedback: { "30": "The agreed product behavior is 60 seconds; keeping 30 would reintroduce the shorter timeout.", configurable: "A configurable value could work in a different design, but both teams agreed this incident requires 60 seconds now." } },
      { id: "finish-merge", objective: "Complete the merge with a commit message describing the resolution.", acceptedCommands: ["git commit -m \"Resolve payment timeout conflict\"", "git commit -m 'Resolve payment timeout conflict'"], hint: "Finish with git commit -m \"Resolve payment timeout conflict\".", success: "The conflict is resolved and the merged behavior is recorded for the team." },
    ],
  },
  {
    id: "time-travel",
    title: "Time Travel",
    eyebrow: "06 / History",
    summary: "Recover a file from a known-good commit without moving the branch.",
    objective: "A recent edit broke the config file. Restore only that file from the previous commit.",
    difficulty: "Intermediate",
    points: 220,
    repository: ["HEAD      ● 91bc2d  Update retry policy", "HEAD~1   ● 0f5c91  Known-good retry config", " M  config/retry.ts"],
    repositorySnapshots: [
      { afterStep: 2, lines: ["HEAD      ● 91bc2d  Update retry policy", "M  config/retry.ts (restored from HEAD~1)"] },
      { afterStep: 3, lines: ["HEAD      ● 7ca13b  Restore known-good retry config", "HEAD~1   ● 91bc2d  Update retry policy", "working tree: clean"] },
    ],
    steps: [
      { id: "inspect-history", objective: "Inspect recent commits to identify the known-good version.", acceptedCommands: ["git log --oneline", "git log --oneline -5"], hint: "Use git log --oneline to scan recent commit messages and IDs.", success: "The history shows the previous commit that contains the known-good file." },
      { id: "restore-file", objective: "Restore only config/retry.ts from the previous commit.", acceptedCommands: ["git restore --source=HEAD~1 -- config/retry.ts", "git checkout HEAD~1 -- config/retry.ts"], hint: "Use git restore --source=HEAD~1 -- config/retry.ts to recover the file without moving HEAD.", success: "The file is restored while the current branch and the rest of the working tree stay in place." },
      { id: "commit-restore", objective: "Save the recovery as \"Restore known-good retry config\".", acceptedCommands: ["git add config/retry.ts && git commit -m \"Restore known-good retry config\"", "git commit -am \"Restore known-good retry config\""], hint: "Stage the restored file, then commit it with a message that explains the recovery.", success: "The recovery is a new commit. Earlier history remains available and unchanged." },
    ],
  },
  {
    id: "bad-commit",
    title: "The Bad Commit",
    eyebrow: "07 / Recovery",
    summary: "Undo a harmful change that is already shared without rewriting history.",
    objective: "A broken configuration change has reached the shared branch. Back it out safely and audibly.",
    difficulty: "Intermediate",
    points: 240,
    repository: ["main  ● f31a42  ❌ Break payment timeout", "      ● 9bc21f  Add authentication", "      ● 8a72c1  Add API configuration"],
    repositorySnapshots: [
      { afterStep: 1, lines: ["main  ● 75cd10  Revert \"Break payment timeout\"", "      ● f31a42  ❌ Break payment timeout", "working tree: clean"] },
      { afterStep: 2, lines: ["main  ● 75cd10  Revert \"Break payment timeout\"", "      ● f31a42  ❌ Break payment timeout", "rollback is auditable · history preserved"] },
    ],
    steps: [
      { id: "revert", objective: "Revert the bad shared commit f31a42.", acceptedCommands: ["git revert f31a42", "git revert HEAD"], hint: "Use git revert f31a42 to create an inverse commit without deleting shared history.", success: "The bad change is undone in a new commit. Teammates can still rely on the existing history." },
      { id: "verify", objective: "Inspect the new history to verify the rollback is recorded.", acceptedCommands: ["git log --oneline", "git log --oneline -5"], hint: "Check the resulting commit history with git log --oneline.", success: "The rollback is visible and auditable. The original bad commit remains in history." },
    ],
  },
  {
    id: "remote-mission",
    title: "Remote Mission",
    eyebrow: "08 / Remotes",
    summary: "Inspect remote updates, integrate them, and publish your feature branch.",
    objective: "Your branch needs the latest origin/main before you publish your reviewed work.",
    difficulty: "Intermediate",
    points: 260,
    branch: "feature/search",
    repository: ["local: feature/search  ●  3 commits ahead", "origin/main           ●  2 commits ahead", "working tree: clean"],
    repositorySnapshots: [
      { afterStep: 1, lines: ["origin/main updated from origin", "feature/search  ● 3 commits ahead", "working tree: clean"] },
      { afterStep: 2, lines: ["feature/search includes origin/main", "feature/search  ● 3 commits ahead", "working tree: clean"] },
      { afterStep: 3, lines: ["origin/feature/search  ← upstream", "feature/search  ● 3 commits ahead", "published for review"] },
    ],
    steps: [
      { id: "fetch", objective: "Download remote references without integrating yet.", acceptedCommands: ["git fetch origin"], hint: "git fetch origin updates remote-tracking refs without changing your branch.", success: "Remote references are refreshed. You can now see the incoming work." },
      { id: "pull", objective: "Integrate origin/main using a fast-forward-only update.", acceptedCommands: ["git pull --ff-only origin main", "git pull --ff-only"], hint: "Use git pull --ff-only so Git refuses an unexpected merge commit.", success: "Your branch includes the latest main changes without creating a merge commit." },
      { id: "push", objective: "Publish feature/search and set its upstream.", acceptedCommands: ["git push -u origin feature/search", "git push --set-upstream origin feature/search"], hint: "Publish and configure tracking with git push -u origin feature/search.", success: "The feature branch is published and tracks its remote counterpart." },
    ],
  },
  {
    id: "lost-work",
    title: "Lost Work",
    eyebrow: "09 / Recovery",
    summary: "Recover a deleted working-tree file without resetting unrelated work.",
    objective: "A teammate deleted a tracked file by accident. Recover the latest committed version without disturbing other edits.",
    difficulty: "Advanced",
    points: 280,
    repository: [" D  src/cart.ts", " M  src/search.ts", "last committed version: HEAD"],
    repositorySnapshots: [
      { afterStep: 2, lines: ["src/cart.ts  ✓ restored from HEAD", " M  src/search.ts"] },
      { afterStep: 3, lines: ["src/cart.ts  ✓ restored from HEAD", " M  src/search.ts (preserved)", "working tree checked with git status"] },
    ],
    steps: [
      { id: "inspect-status", objective: "Inspect the worktree to identify what was deleted.", acceptedCommands: ["git status"], hint: "git status confirms the tracked deletion and reveals unrelated edits.", success: "You identified the deleted cart module and a separate search change to preserve." },
      { id: "restore-cart", objective: "Restore the deleted file from HEAD only.", acceptedCommands: ["git restore --source=HEAD -- src/cart.ts", "git restore src/cart.ts", "git checkout -- src/cart.ts"], hint: "Restore just the deleted tracked file with git restore --source=HEAD -- src/cart.ts.", success: "The cart file is back. The unrelated search edit is still intact." },
      { id: "verify-recovery", objective: "Check the worktree after recovery.", acceptedCommands: ["git status"], hint: "Run git status again to confirm the deletion is gone and unrelated work remains.", success: "The lost file is recovered and the teammate's other work was not reset." },
    ],
  },
  {
    id: "production-emergency",
    title: "Production Emergency",
    eyebrow: "10 / Final mission",
    summary: "Contain an incident with a focused fix and preserve the team's history.",
    objective: "A deployed payment timeout change caused an outage. Create a hotfix branch, revert the bad commit, and publish the fix for review.",
    difficulty: "Advanced",
    points: 320,
    branch: "main",
    branchProgression: [{ afterStep: 1, branch: "hotfix/payment-timeout" }],
    repository: ["main  ● f31a42  ❌ Payment timeout regression", "      ● 9bc21f  Add authentication", "incident: checkout failures are rising"],
    repositorySnapshots: [
      { afterStep: 1, lines: ["hotfix/payment-timeout  ← HEAD", "main  ● f31a42  ❌ Payment timeout regression", "incident: checkout failures are rising"] },
      { afterStep: 2, lines: ["hotfix/payment-timeout  ● 6a0b31  Revert payment timeout", "main  ● f31a42  ❌ Payment timeout regression", "shared history preserved"] },
      { afterStep: 3, lines: ["origin/hotfix/payment-timeout  ← upstream", "hotfix/payment-timeout  ● 6a0b31  Revert payment timeout", "ready for expedited review"] },
    ],
    steps: [
      { id: "hotfix-branch", objective: "Create a hotfix branch from the current production point.", acceptedCommands: ["git switch -c hotfix/payment-timeout"], hint: "Isolate the production repair with git switch -c hotfix/payment-timeout.", success: "The hotfix is isolated from other development work." },
      { id: "undo-bad-commit", objective: "Undo the regression using a new inverse commit.", acceptedCommands: ["git revert f31a42", "git revert HEAD"], hint: "Revert the deployed commit; do not reset or rewrite the shared production branch.", success: "The incident-causing change is undone without rewriting shared history." },
      { id: "publish-hotfix", objective: "Publish the hotfix branch so the team can review and deploy it.", acceptedCommands: ["git push -u origin hotfix/payment-timeout", "git push --set-upstream origin hotfix/payment-timeout"], hint: "Publish the isolated repair with git push -u origin hotfix/payment-timeout.", success: "The hotfix is ready for expedited review, checks, and deployment." },
    ],
  },
];
